### ISSUE TITLE
How to save to a database ?

### ISSUE THREAD

**Issue by tangi75** [expfactory/expfactory-python#126]
Hello,

I'd like to save the test results to a database, like what is described with jsPsych at http://docs.jspsych.org/features/data/#storing-data-permanently-in-a-mysql-database

I found the local csv saving in localbattery.html (call to jsPsych.data.localSave) but nothing like a call to a server-side script. Is it to be implemented manually ?

It's still not clear for me also what the database is used for by batteries ? Input data to be used by the test or test results data ?

**Comment by vsoch** [comment]
Hey @tangi75 !

I'm guessing that you are using the command line tool, eg:

```
  expfactory --run --experiments stroop,..
```

in which case you are correct, the experiments that deploy are in a battery that is served locally, with data saved to `.csv` at the end. The template that you found, localbattery.html, is indeed the right one!

Let's chat about the kind of functionality that you are looking to have to move forward. The example script that Josh suggests using is a good solution if you have a secure server (or local machine) from which you are deploying the battery. What you would need to do is setup the database separately, and then export the credentials to environmental variables. Eg something like:

```
  echo "export dbuser=tangy" >> ~/.bashrc
  echo "export dbpass=pancakes" >> ~/.bashrc
```

and then of course the `~/.bashrc` is sourced when you start things up, and the environmental variables are available for the script. If you are looking for a more substantial set up, then you probably want to use our dockerized application, expfactory-docker.  It comes packaged with a database setup, and you would need to run and set up the container yourself (with any help needed of course, of course). Something to look forward to - I am teaming up with another open source experiment software group and we hope to be able to offer this sooner than later, integrated with Open Science Framework and cool stuff like that  :)

In the meantime - how about I'll make a command line option to deploy to a local database, defined by environmental variables, and would you be available for testing? If it's good, we can release with the package and offer to others as well.

**Comment by vsoch** [comment]
Also - this would need a local installation of php to run locally (vs. most servers come installed with it). So please let me know where you intend to run this! If it's still local, you might do better off running the docker image.

**Comment by tangi75** [comment]
Hi Vanessa,

Thank you for your explanations. I indeed want to deploy expfactory to a secure server that already supports python, php and mysql.

For some obscure reason I haven't investigated yet, a "Folder" deployment doesn't work on my setup (maybe due to my incomplete port to Python 3). Nevertheless, the Vagrant deployment works fine and reading the generated Vagrantfile was insightful and I think I now see how to deploy to a server.
I'd be glad to test your "command line option to deploy to a local database" of course!

To provide you with more insights, I'm trying to integrate expfactory with https://github.com/campsych/concerto-platform/wiki. Both coexisting on the same server and database as a first step, and developing a custom 'Expfactory' Concerto node as a second step to have things more integrated.

**Comment by vsoch** [comment]
Ah, this is super neat! I think that we will go the farthest if I can come up with a recipe to export an experiment in the right format to be a Concerto "Node."

Do you have a folder / example of what a node-ized experiment should looked like? Their docs are pretty sparse about it.

**Comment by tangi75** [comment]
I recently managed to create (or rather customized based on the regulat questionnaire node) my own Concerto node to make ipsative tests. This is something I promised David Stillwell to document on the concerto github very soon.
Basically a typical test node is made of three parts: a main node to be used in the workflow, a wizard node that drives the configuration of the main node and a source node (in R).
I've not tried to node-ize an experiment yet. That's my next challenge once I succeed to deploy expfactory on my concerto server.

**Comment by vsoch** [comment]
Ok, I think I have a good suggestion for a plan of action:
1. First write the docs about how to create the node. Send me the link, along with a repo/tarball of the node so I can look at the specifics. It would be great if you could share some insight about how the experiments move from one to the other (eg, what are the inputs/outputs of a node?)
2. From this I can determine how to most quickly get from expfactory --> Concerto node, and create a recipe of sorts.

Without knowing much about Concerto, my thinking is that either expfactory will export exactly the format for a Concerto node as an option, or if there is something that needs to be configured over there, it can export a general thing that can easily integrated. Let me know your thoughts.

**Comment by tangi75** [comment]
Perfect! I'll do step 1 tomorrow.

**Comment by vsoch** [comment]
sounds good!

**Comment by tangi75** [comment]
Here it is the part about node creation :
[Custom-node-creation-part-1.pdf](https://github.com/expfactory/expfactory-python/files/558260/Custom-node-creation-part-1.pdf)

I'm writing the part about workflows and node i/o.

**Comment by tangi75** [comment]
Here is the workflow tutorial :

[Test flow tutorial.pdf](https://github.com/expfactory/expfactory-python/files/558746/Test.flow.tutorial.pdf)

**Comment by tangi75** [comment]
And finally the R code of the Ipsative_questionnaire test logic (adapted from the standard questionnaire) as described in the Custom-node-creation-part-1.pdf.

[ipsative questionnaire - test logic.r.txt](https://github.com/expfactory/expfactory-python/files/558780/ipsative.questionnaire.-.test.logic.r.txt)

This is a rather complex node, being entirely configurable using the web interface (saving the configuration into the database), having input and output parameters, getting question data from the dabase, etc. It will give you and idea of what can be node in a Concerto node.

**Comment by tangi75** [comment]
So a node creation (even from scratch) is mostly performed through Concerto web interface, even data tables creation and loading is done this way (through the Data tables tab of the admin interface).

You may have R code in : 
- the test logic of a Source test node
- the data links between nodes

You may have HTML/CSS/Javascript code in : 
- the head and body sections of a template (see https://github.com/campsych/concerto-platform/wiki/Templates-introduction)

Concerto is indeed a neat platform.

**Comment by tangi75** [comment]
FYI, I've almost complete the integration with a local database.

I didn't try to add another option to the expfactory command because I think it's already too much of a [swiss army knife](https://sourcemaking.com/antipatterns/swiss-army-knife) in my opinion and thus difficult to use.

I instead wrote a very small battery generation script that expects the repos to be already available and calls directly generate_base (to bypass the repos downloads at every execution) and template_experiments with a custom version of localbattery.html embedding javascript functions to get the subject id from the query string and to call the server-side script (from http://docs.jspsych.org/features/data/#storing-data-permanently-in-a-mysql-database) that saves the json result to the database. The generated battery is thus usable by multiple different subjects and a single instance of it may be delivered by a web server to all of them.

I still have to do a bit of apache/mysql configuration to make this work along with Concerto on the same server for my first step to be really done. I'll share the code then.

This hack gave me a better understanding of expfactory and I'd be happy to work with you on node-izing the expfactory experiments.

**Comment by vsoch** [comment]
Ok great! If getting it to work is simply a matter of:
- supporting a custom template for battery generation
- then some clear steps with instructions for those interested in Concerto

then we can easily add the template, and make a recipe (and add to docs for users) to support Concerto.

Thanks for your quick work on this! I'll wait to hear from you, with code, before moving forward. Just FYI - I'm pretty tied up until mid week with other projects, so no rush on this.

**Comment by tangi75** [comment]
Well, not exactely. As of today, I can just save to the Concerto database. Expfactory experiments cannot be integrated into a Concerto test flow if not node-ized. 
Another workaround hack could possibly be to create redirection nodes to temporarily leave Concerto for expfactory and go back to the test flow on batterry completion. But the node-ized approach would be much smarter.
I'll get back to you with code. Thanks for your support and good luck on your other projects.

**Comment by tangi75** [comment]
HI Vanessa.

My code and documentation are ready. Could you grant me with the required priviledges to make a pull request?

$ git diff --name-only master
doc/source/deployment.rst
expfactory-server/concerto.conf
expfactory-server/create_expfactory_table.sql
expfactory-server/database_connect.php
expfactory-server/save_data.php
expfactory/battery.py
expfactory/templates/webserver-battery-template.html
script/run_battery.py
script/setup_battery_for_webserver.py

The only existing files I've touched are deployment.rst (to add some doc at the end) and battery.py (to add a missing "valid_games = []" after line 43).

**Comment by vsoch** [comment]
Awesome!  Hmm you should not need special permissions beyond forking the repo to your name, checking out a branch for your changes, and then clicking new pull request to upstream master! Do you want to give that a go?

**Comment by vsoch** [comment]
@tangi75  - One more nice thing to add would be some kind of check to ensure that the call to submit the data is coming from the experiment page after the user has finished the experiment, so that you can't spam the URL to submit to the database.  Do you have any suggestions?

**Comment by vsoch** [comment]
Probably there is no perfect solution, but what about:

```
  // @vsoch adding call to prevent execution of script directly
  define('AJAX_REQUEST', isset($_SERVER['HTTP_X_REQUESTED_WITH']) && strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) == 'xmlhttprequest');
  if(!AJAX_REQUEST) {die();}
```

at the top of save_data.php?

**Comment by tangi75** [comment]
It shouldn't harm. This makes me think that I forgot to test whether $to_insert['json'] is empty or not. We shouldn't insert empty data.

**Comment by tangi75** [comment]
I see no HTTP_X_REQUESTED_WITH header (tested with Chrome) : 
Accept:_/_
Accept-Encoding:gzip, deflate, br
Accept-Language:fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4
Connection:keep-alive
Content-Length:97667
Content-Type:application/x-www-form-urlencoded; charset=UTF-8
DNT:1
Host:localhost:8080
Origin:http://localhost:8484
Referer:http://localhost:8484/
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36

Not sure it is a good idea: risk of abusive blocking for an easy to bypass protection. See http://stackoverflow.com/questions/26547369/how-to-find-out-if-a-request-is-an-ajax-request.

**Comment by vsoch** [comment]
I think we merged this contribution, and forgot to close! Huge (and very belated) thanks @tangi75
