### ISSUE TITLE
Experiments can't be run in non-random order

### ISSUE THREAD

**Issue by earcanal** [expfactory/expfactory-python#134]
To avoid order effects `expfactory --run --experiments ...` randomises experiment order.  This behaviour is a little unclear (e.g. not mentioned in `expfactory --help`).  There are also cases where specifying a specific order is useful, for example, where performance on one task should affect the outcome of a subsequent task.

Can I suggest the following additional `expfactory` option

```--no-random don't randomise experiment order (default is to randomise which minimises order effects)```

**Comment by vsoch** [comment]
hey @earcanal ! I have the early (alpha?) version of the experiments container ready to go! I've written up some documentation for you to get started:

https://expfactory.github.io/expfactory/

This is truly a reproducible experiments container, meaning you generate it once, and it's not going to run into a lot of these issues. I'd appreciate feedback on all things, and importantly, suggestions / requests for your use case. I'd like to get feedback from a handful of users, do a bit more work, and then port the rest of the library (experiment, games, surveys) over to the new version. Thanks for your help with this! You can close all your issues here and re-open them [at the new repository](https://www.github.com/expfactory/expfactory).

**Comment by vsoch** [comment]
Issue moved to https://github.com/expfactory/expfactory/issues/35
