### ISSUE TITLE
Fail to launch expfactory because AttributeError

### ISSUE THREAD

**Issue by rmasiso** [expfactory/expfactory-python#135]
Hello!

I've been trying to set up expfactory for a bit now and I keep running into some hiccups. 

First since expfactory is configured for py27, I created a virtual environment and have been running everything in that environment. 

My expfactory, by '`which expfactory`' is found here:

`/Users/RMASISO/anaconda/envs/py27/bin/expfactory`

as soon as I launch any sort of command I get this AttributeError which I can't seem to overcome.
Any command whether its `expfactory` or `expfactory --run  --experiments stroop,nback --folder expfactory-experiments --battery expfactory-battery` gives me this error:

```
Generating custom battery selecting from experiments for maximum of 99999 minutes, please wait...

Traceback (most recent call last):
  File "/Users/RMASISO/anaconda/envs/py27/bin/expfactory", line 11, in <module>
    load_entry_point('expfactory==2.5.46', 'console_scripts', 'expfactory')()
  File "/Users/RMASISO/anaconda/envs/py27/lib/python2.7/site-packages/expfactory/scripts.py", line 117, in main
    time=args.time)

  File "/Users/RMASISO/anaconda/envs/py27/lib/python2.7/site-packages/expfactory/views.py", line 118, in run_battery
    time=time)

  File "/Users/RMASISO/anaconda/envs/py27/lib/python2.7/site-packages/expfactory/battery.py", line 90, in generate_local
    add_surveys=False)

  File "/Users/RMASISO/anaconda/envs/py27/lib/python2.7/site-packages/expfactory/battery.py", line 29, in generate_base
    tmpdir = custom_battery_download()

  File "/Users/RMASISO/anaconda/envs/py27/lib/python2.7/site-packages/expfactory/vm.py", line 37, in custom_battery_download
    download_repo(repo,"%s/%s/" %(tmpdir,repo))

  File "/Users/RMASISO/anaconda/envs/py27/lib/python2.7/site-packages/expfactory/vm.py", line 23, in download_repo
    return Repo.clone_from("https://github.com/expfactory/expfactory-%s" %(repo_type), destination)

AttributeError: type object 'Repo' has no attribute 'clone_from'
```

Any idea how to get around this? 

I've made sure I'm up to date with git.

Thanks a lot!

**Comment by vsoch** [comment]
hey @rmasiso - I think you want an (earlier) version of git - which are you using?

```
git.__version__
'1.0.1'
```

I too am not happy with 2.7 and the many updates that are needed, and can only say I'm working my best (in free time!) to fix things up! I do see the need and promise I'll do my best.

**Comment by rmasiso** [comment]
Thanks for getting back to me!

The version I'm running:
```
$ git --version
git version 2.10.1
```
I installed an older version of git:
```$ git --version
git version 2.7.1
```

and still I get the error. 

I then installed an even older version
```
$ git --version
git version 1.9.5
```

..and still no luck.

**Comment by vsoch** [comment]
could you please try the version I referenced above?

```
pip install gitpython==1.01
```

**Comment by vsoch** [comment]
and and this is the version of gitpython, not git! oup :)

**Comment by rmasiso** [comment]
My mistake! 
I ran:
`pip install gitpython==1.0.1`
..and, it works!

Thanks a lot. I'll make sure to post if anything else comes up!

**Comment by vsoch** [comment]
Great! I'll keep plugging away at making the core software better. Please ping again if there are other issues!
