### ISSUE TITLE
Upgrade selenium

### ISSUE THREAD

**Issue by rwblair** [expfactory/expfactory-python#136]
Current version of selenium is using firefox 38.0.5. There are starting to be new features in javascript that aren't supported in this version of firefox. 

current selenium is at 2.53.6 The next version of selenium 2 drops use of UnexpectedAlertPresentException. I think they handle unexpected alerts automatically now will need to check.

**Comment by vsoch** [comment]
sounds good! Just to keep you in the loop, the next version for experiments will be more general and modular, meaning that an experiment to pass must have certain elements/ids that are triggers to start, top, etc, and then it will be easier for the robot to move through. And for tests, given that jspsych will be one of many things supported (arguably the user should be able to use whatever web framework he she wants) we will provide a general framework for the user to define tests for the specific experiment.

**Comment by vsoch** [comment]
and testing will be easier too, because each experiment will have it's own repo (and thus will contain its own tests within that!)

**Comment by rwblair** [comment]
I was mistaken, turns out the browser version was coming from the circleci container. I switched the container in cricle from ubuntu 12 to 14 which has more modern browsers installed.
