### ISSUE TITLE
Broken link in docs "Try our paradigms"

### ISSUE THREAD

**Issue by jyeatman** [expfactory/expfactory-python#142]
## Version of Experiment Factory:

Current

### Expected behavior

[Docs page ](https://expfactory.readthedocs.io/en/latest/getting-started.html#getting-started)links to http://expfactory.github.io/table.html which is broekn

### Actual behavior

Broken link

### Steps to reproduce behavior

Write here.

**Comment by vsoch** [comment]
Thanks for reporting the broken link! I no longer maintain this, but I'm happy to fix (and it should be resolved now). Closing issue.

**Comment by jyeatman** [comment]
another broken link in the docs:
https://expfactory.github.io/table.html

**Comment by vsoch** [comment]
I don't see that link with grep - perhaps refresh your browser and look at the page again. If the link is indeed there, please point me to it in https://github.com/expfactory/expfactory-python/tree/master/doc because I don't see it. Thanks!
