### ISSUE TITLE
Validate issue

### ISSUE THREAD

**Issue by IanEisenberg** [expfactory/expfactory-python#45]
I am running expfactory --validate and receiving an error like so:
WARNING: config.json is missing field name: psychological_refractory_period
WARNING: config.json is missing field reference: psychological_refractory_period

On circle it says:
config.json could not be found in /home/ubuntu/expfactory-experiments/web
/home/ubuntu/expfactory-experiments/web is not an experiment.
Found 79 valid experiments
Directory not copied. Error: [Errno 2] No such file or directory: '/tmp/tmp9Zb8Nv/experiments/local_global_shape'
config.json could not be found in /tmp/tmp9Zb8Nv/experiments/local_global_shape

The config file is correct (and existing) however. You can see the PR here: https://github.com/IanEisenberg/expfactory-experiments/blob/fixes/local_global_shape/config.json

Not sure what's going on

**Comment by vsoch** [comment]
> I am running expfactory --validate and receiving an error like so:
> WARNING: config.json is missing field name: psychological_refractory_period
> WARNING: config.json is missing field reference: psychological_refractory_period

This is ok, these are just warnings.

> On circle it says:
> config.json could not be found in /home/ubuntu/expfactory-experiments/web
> /home/ubuntu/expfactory-experiments/web is not an experiment.

This is also ok, that message was always there

> Found 79 valid experiments
> Directory not copied. Error: [Errno 2] No such file or directory: '/tmp/tmp9Zb8Nv/experiments/local_global_shape'
> config.json could not be found in /tmp/tmp9Zb8Nv/experiments/local_global_shape
> 
> The config file is correct (and existing) however. You can see the PR here: https://github.com/IanEisenberg/expfactory-experiments/blob/fixes/local_global_shape/config.json
> 
> Not sure what's going on

I think I have an idea - could you link me to the circle?

**Comment by vsoch** [comment]
I found it - looking into this now.

**Comment by IanEisenberg** [comment]
Great, thanks. Just want to see that green check :)

**Comment by vsoch** [comment]
ok it looks like the experiment_repo argument isn't passing through as we would want. If you can hold off merging anything for a few minutes, I need to do some tests.

**Comment by IanEisenberg** [comment]
Will do.

On Wed, Feb 17, 2016 at 2:04 PM, Vanessa Sochat notifications@github.com
wrote:

> ok it looks like the experiment_repo argument isn't passing through as we
> would want. If you can hold off merging anything for a few minutes, I need
> to do some tests.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/expfactory/expfactory-python/issues/45#issuecomment-185428281
> .

## 

Best,
Ian

**Comment by vsoch** [comment]
Found the bug, this needs to be `experiment_folder`:

https://github.com/expfactory/expfactory-python/blob/master/expfactory/views.py#L142

I missed this detail when I added the variable experiment_folder that would give the user the option to generate a web interface for a custom/local folder.

**Comment by vsoch** [comment]
Fixed!

https://circleci.com/gh/expfactory/expfactory-experiments/359

:)
